-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 17:57:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `heslo` VARCHAR(45) NULL,
  `rodne_cislo` VARCHAR(45) NULL,
  `jmeno` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NULL,
  `datum_narozeni` DATETIME NULL,
  `adresa` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `role` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kurz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kurz` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `zkratka` VARCHAR(45) NULL,
  `nazev` VARCHAR(45) NULL,
  `popis` VARCHAR(45) NULL,
  `cena` INT NULL,
  `limit` INT NULL,
  `garant_ID` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_kurz_uzivatel1`
    FOREIGN KEY (`garant_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zadost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zadost` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `datum` DATETIME NULL,
  `typ` INT NULL,
  `popis` VARCHAR(45) NULL,
  `uzivatel_ID` INT NOT NULL,
  `kurz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_zadost_uzivatel`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zadost_kurz1`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mistnost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mistnost` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `typ` INT NULL,
  `popis` VARCHAR(45) NULL,
  `kapacita` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`termin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `typ` INT NULL,
  `datum` DATETIME NULL,
  `popis` VARCHAR(45) NULL,
  `hodnoceni` INT NULL,
  `kapacita` INT NULL,
  `kurz_ID` INT NOT NULL,
  `mistnost_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_termin_kurz1`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_termin_mistnost1`
    FOREIGN KEY (`mistnost_ID`)
    REFERENCES `mydb`.`mistnost` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lektor_uci_v_kurzu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lektor_uci_v_kurzu` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `kurz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_kurz_uzivatel1`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_kurz_kurz1`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_navstevuje_kurz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_navstevuje_kurz` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `kurz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_kurz_uzivatel2`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_kurz_kurz2`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uzivatel_registruje_termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel_registruje_termin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `termin_ID` INT NOT NULL,
  `datum` DATETIME NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_termin_uzivatel1`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_termin_termin1`
    FOREIGN KEY (`termin_ID`)
    REFERENCES `mydb`.`termin` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uzivatel_ma_hodnoceni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel_ma_hodnoceni` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `termin_ID` INT NOT NULL,
  `body` INT NULL DEFAULT 0,
  `datum` DATETIME NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_termin_uzivatel2`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_termin_termin2`
    FOREIGN KEY (`termin_ID`)
    REFERENCES `mydb`.`termin` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
