-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 17:57:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `heslo` VARCHAR(45) NULL,
  `rodne_cislo` VARCHAR(45) NULL,
  `jmeno` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NULL,
  `datum_narozeni` DATETIME NULL,
  `adresa` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `role` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kurz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kurz` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `zkratka` VARCHAR(45) NULL,
  `nazev` VARCHAR(45) NULL,
  `popis` VARCHAR(45) NULL,
  `cena` INT NULL,
  `limit` INT NULL,
  `garant_ID` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_kurz_uzivatel1`
    FOREIGN KEY (`garant_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zadost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zadost` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `datum` DATETIME NULL,
  `typ` INT NULL,
  `popis` VARCHAR(45) NULL,
  `uzivatel_ID` INT NOT NULL,
  `kurz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_zadost_uzivatel`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zadost_kurz1`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mistnost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mistnost` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `typ` INT NULL,
  `popis` VARCHAR(45) NULL,
  `kapacita` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`termin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `typ` INT NULL,
  `datum` DATETIME NULL,
  `popis` VARCHAR(45) NULL,
  `hodnoceni` INT NULL,
  `kapacita` INT NULL,
  `kurz_ID` INT NOT NULL,
  `mistnost_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_termin_kurz1`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_termin_mistnost1`
    FOREIGN KEY (`mistnost_ID`)
    REFERENCES `mydb`.`mistnost` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lektor_uci_v_kurzu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lektor_uci_v_kurzu` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `kurz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_kurz_uzivatel1`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_kurz_kurz1`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_navstevuje_kurz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_navstevuje_kurz` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `kurz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_kurz_uzivatel2`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_kurz_kurz2`
    FOREIGN KEY (`kurz_ID`)
    REFERENCES `mydb`.`kurz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uzivatel_registruje_termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel_registruje_termin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `termin_ID` INT NOT NULL,
  `datum` DATETIME NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_termin_uzivatel1`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_termin_termin1`
    FOREIGN KEY (`termin_ID`)
    REFERENCES `mydb`.`termin` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uzivatel_ma_hodnoceni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel_ma_hodnoceni` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_ID` INT NOT NULL,
  `termin_ID` INT NOT NULL,
  `body` INT NULL DEFAULT 0,
  `datum` DATETIME NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_uzivatel_has_termin_uzivatel2`
    FOREIGN KEY (`uzivatel_ID`)
    REFERENCES `mydb`.`uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_termin_termin2`
    FOREIGN KEY (`termin_ID`)
    REFERENCES `mydb`.`termin` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DELETE FROM `mydb`.`kurz`;
DELETE FROM `mydb`.`uzivatel`;
ALTER TABLE `mydb`.`uzivatel` AUTO_INCREMENT = 1;
ALTER TABLE `mydb`.`kurz` AUTO_INCREMENT = 1;

INSERT INTO `mydb`.`uzivatel`
(`login`, `heslo`, `rodne_cislo`, `jmeno`, `prijmeni`, `datum_narozeni`, `adresa`, `email`, `role`) VALUES
('teacher1', '123456', '000111/1234', 'Ucitel', 'Prvni', '1980-01-01 00:00:00', 'Brno', 'teacher1@wis.cz', 2),
('teacher2', '123456', '000222/1234', 'Ucitel', 'Druhy', '1981-01-01 00:00:00', 'Brno', 'teacher2@wis.cz', 2),
('teacher3', '123456', '000333/1234', 'Ucitel', 'Treti', '1982-01-01 00:00:00', 'Brno', 'teacher3@wis.cz', 2);

INSERT INTO `mydb`.`kurz` (`zkratka`, `nazev`, `popis`, `cena`, `limit`, `garant_ID`) VALUES
('IZP', 'Základy programování', 'Popis IZP.....', 5, 500, 1),
('IDM', 'Diskrétní matematika', 'Popis IDM.....', 4, 450, 1),
('ILG', 'Lineární algebra', 'Popis ILG.....', 6, 400, 3),
('IUS', 'Úvod do SW inženýrství', 'Popis IUS.....', 5, 350, 3),
('IEL', 'Elektronika pro informační technologie', 'Popis IEL.....', 4, 300, 3),
('INC', 'Návrh číslicových systémů', 'Popis INC.....', 6, 400, 2),
('IOS', 'Operační systémy', 'Popis IOS.....', 5, 450, 1),
('ITW', 'Tvorba webových stránek', 'Popis ITW.....', 4, 300, 2),
('IIS', 'Informační systémy', 'Popis IIS.....', 6, 500, 2),
('IDS', 'Databázové systémy', 'Popis IDS.....', 5, 400, 2),
('IPK', 'Počítačové komunikace a sítě', 'Popis IPK.....', 6, 450, 3),
('ISA', 'Síťové aplikace', 'Popis ISA.....', 5, 350, 3);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
